record:
    path: "./keploy-tests"
    # mandatory
    command: "<path to your node> server"
    proxyport: 0
    containerName: ""
    networkName: ""
    delay: 5
    buildDelay: 30s
    passThroughPorts: []
    filters:
        ReqHeader: []
        urlMethods: {}
test:
    path: "./keploy-tests"
    # mandatory
    command: "<path to your node> server"
    proxyport: 0
    containerName: ""
    networkName: ""
    # example: "test-set-1": ["test-1", "test-2", "test-3"]
    tests:
    # to use globalNoise, please follow the guide at the end of this file.
    globalNoise:
        global:
            body: {}
            header: {}
    delay: 5
    buildDelay: 30s
    apiTimeout: 5
    passThroughPorts: []
    withCoverage: false
    coverageReportPath: ""

  # Example on using globalNoise
  # globalNoise:
  #    global:
  #      body: {
  #         # to ignore some values for a field,
  #         # pass regex patterns to the corresponding array value
  #         "url": ["https?://\S+", "http://\S+"],
  #      }
  #      header: {
  #         # to ignore the entire field, pass an empty array
  #         "Date": [],
  #       }
  #     # to ignore fields or the corresponding values for a specific test-set,
  #     # pass the test-set-name as a key to the "test-sets" object and
  #     # populate the corresponding "body" and "header" objects
  #     test-sets:
  #       test-set-1:
  #         body: {
  #           # ignore all the values for the "url" field
  #           "url": []
  #         }
  #         header: {
  #           # we can also pass the exact value to ignore for a field
  #           "User-Agent": ["PostmanRuntime/7.34.0"]
  #         }
